In [55]:
# Importação de bibliotecas
import numpy as np # np sera o apelido

In [56]:
temperaturas = np.array([30, 40, 50, 60, 70, 80, 90, 100])
print(temperaturas)
print(type(temperaturas))

[ 30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


In [57]:
# Media aritmetica
media = np.mean(temperaturas)
print(f"{media:.2f}")

65.00


In [58]:
# Maior valor
maior_valor = np.max(temperaturas)
print(maior_valor)

100


In [59]:
# Menor valor
menor_valor = np.min(temperaturas)
print(menor_valor)

30


In [60]:
salarios = np.array([2,3,4,5,1,500])
media_salarios = np.mean(salarios)
print(f"{media_salarios:.2f}")

85.83


In [61]:
mediana = np.median(salarios)
print(salarios)

[  2   3   4   5   1 500]


Desafio final
- criar um array de habitantes de 5 cidades do estado de SP
- maior população 
- menor população
- mediana

In [62]:
import numpy as sp 


In [63]:
cidades = sp.array([11451999, 1291771, 1139047,810729, 748919])

print(cidades)

maior_pop = sp.max(cidades)
print(f"A maior é: {maior_pop}")

menor_pop = sp.min(cidades)
print(f"A menor é: {menor_pop}")

mediana_pop = sp.median(cidades)
print(f"A mediana é: {mediana_pop}")

media_pop = sp.mean(cidades)
print(f"A media é: {media_pop}")

[11451999  1291771  1139047   810729   748919]
A maior é: 11451999
A menor é: 748919
A mediana é: 1139047.0
A media é: 3088493.0


In [64]:
import pandas as pd
df = pd.read_csv(r".\data\dataset_aula1_numpy_pandas.csv")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha
0,1,Montagem,72.62,41.77,111,0
1,2,Usinagem,81.65,34.08,128,0
2,3,Usinagem,68.87,39.44,159,0
3,4,Usinagem,66.84,34.52,98,0
4,5,Usinagem,66.23,31.57,94,0


In [65]:
df[["temperatura_c","falha"]]

,temperatura_c,falha
0,72.62,0
1,81.65,0
2,68.87,0
3,66.84,0
4,66.23,0
5,64.79,0
6,85.02,1
7,60.31,0
8,75.84,0
9,68.38,1


In [68]:
df["classificacao_temperatura"] = np.where(df["temperatura_c"]>=75,"temperatura alta","temperatira baixa")
df.head()

,id_registro,setor,temperatura_c,tempo_ciclo_s,producao_dia,falha,classificacao_temperatura
0,1,Montagem,72.62,41.77,111,0,temperatira baixa
1,2,Usinagem,81.65,34.08,128,0,temperatura alta
2,3,Usinagem,68.87,39.44,159,0,temperatira baixa
3,4,Usinagem,66.84,34.52,98,0,temperatira baixa
4,5,Usinagem,66.23,31.57,94,0,temperatira baixa
